### PR TITLE
Added pillow to requirements_to_build_windows_exe.txt file and update…

### PR DESCRIPTION
**Pull request by earlyraven**
Fixes error when building Windows .exe file from a Windows system without pillow installed.

This pull request addresses the 'ModuleNotFoundError' and 'ValueError' that occur when attempting to build the .exe file on a Windows system without pillow installed. The proposed changes include automatically installing pillow before running pyinstaller, ensuring the availability of the 'PIL' module and enabling seamless image format conversion. These enhancements aim to facilitate successful .exe file generation without requiring manual intervention.

Please review and merge this pull request at your convenience.

### CODE REVIEW

**Comment by halfburnttoast** [comment]
Good catch, thanks!

**Comment by earlyraven** [comment]
You're welcome.  I'm curious if there's any other features you were hoping to have added to this.  I'm looking for open-source projects to contribute to.

**Comment by halfburnttoast** [comment]
Sure! There are few features that have been on the list but I just hadn’t gotten around to them.

- Ability for users to select custom colors for sprites in colorblind mode. Right now all the colorblind-friendly sprites are static. Maybe by adding color hue sliders to the menu.
- Animated sprites.
- Separate music/sound effect volume sliders.
- Showing the solution without user-placed marks, similar to how it’s done in Dungeons and Diagrams.
- Real-time map variations such as flipping/rotating.

Some of theses range from small changes to significant features. The map variants is one I worked on in the past but haven’t finished.

**Comment by earlyraven** [comment]
Could you elaborate a bit on what you had in mind for animated sprites?  Would you want it to support a sprite-sheet and simply loop through them all, or did you have something more complex or something else in mind?  Do you have any preference toward keeping the current graphics or using a different sprite-sheet for the graphics?  I'll take a deeper look at the code-base this weekend and see what I'd be comfortable with.

**Comment by halfburnttoast** [comment]
So, I don’t know if you’ve played the original game. But, in Dungeons and Diagrams the characters on the board do have some sprite animations that include an idle loop and and victory loop. The animations are pretty low frame rate. 

I didn’t take a whole lot of time looking at sprites to use for this game. Most of the sprites are from DCSS which I don’t think have any animated sprites. 

I just thought it might be something cool to try. I haven’t looked a the codebase for a while, but I don’t think it’s setup to handle sprite sheets and animation. There would likely need to be some restructuring of the update loop to allow for it.

**Pull request merged**
